// Generates ready-to-use Infrastructure-as-Code files for a catalog template so
// a user can provision / manage the resource from their tool of choice. Every
// generated file targets the CPC REST API and authenticates with a Personal
// Access Token, so the whole application is drivable from Terraform, Ansible,
// Pulumi or a plain REST client.

export const IAC_TOOLS = [
  { id: "terraform", label: "Terraform", ext: "tf", filename: "main.tf" },
  { id: "ansible", label: "Ansible", ext: "yml", filename: "playbook.yml" },
  { id: "pulumi", label: "Pulumi (TypeScript)", ext: "ts", filename: "index.ts" },
  { id: "curl", label: "REST (cURL)", ext: "sh", filename: "provision.sh" },
];

export const isIacTool = (t) => IAC_TOOLS.some((x) => x.id === t);

// Work out the provisioning endpoint + request body for a template + kind.
function resolveTarget(kind, template) {
  const isInternal = template?.provider === "internal";
  if (kind === "vm" && isInternal) {
    return {
      path: "/api/provision/internal",
      body: { templateId: template.id, hostname: "${HOSTNAME}", cpu: "${CPU}", memoryGB: "${MEMORY_GB}", diskGB: "${DISK_GB}" },
    };
  }
  if (kind === "container") {
    return {
      path: "/api/provision/container",
      body: { templateId: template.id, hostname: "${HOSTNAME}", cpu: "${CPU}", memoryGB: "${MEMORY_GB}" },
    };
  }
  if (kind === "stack") {
    return {
      path: "/api/provision/stack",
      body: { stackId: template.id, hostnamePrefix: "${HOSTNAME}", cpu: "${CPU}", memoryGB: "${MEMORY_GB}", diskGB: "${DISK_GB}" },
    };
  }
  return {
    path: "/api/provision/vm",
    body: { templateId: template.id, hostname: "${HOSTNAME}", cpu: "${CPU}", memoryGB: "${MEMORY_GB}", diskGB: "${DISK_GB}", environment: "${ENVIRONMENT}", username: "${USERNAME}" },
  };
}

const j = (obj) => JSON.stringify(obj);

function terraform(ctx) {
  const { baseUrl, kind, template, path, body } = ctx;
  const isVm = body.environment !== undefined;
  const idKey = kind === "stack" ? "stackId" : "templateId";
  const hostKey = kind === "stack" ? "hostnamePrefix" : "hostname";

  // Body as a single-quoted JS string so ${var.x} stays literal HCL.
  const pairs = [
    '"' + idKey + '":"' + template.id + '"',
    '"' + hostKey + '":"${var.hostname}"',
    '"cpu":${var.cpu}',
    '"memoryGB":${var.memory_gb}',
  ];
  if (kind !== "container") pairs.push('"diskGB":${var.disk_gb}');
  if (isVm) { pairs.push('"environment":"${var.environment}"'); pairs.push('"username":"${var.username}"'); }
  const bodyJson = "{" + pairs.join(",") + "}";

  const lines = [
    "# " + template.name + " — provision via CPC (" + kind + ")",
    "# Generated by Colruyt Private Cloud. Drive the CPC API from Terraform.",
    "",
    "terraform {",
    '  required_version = ">= 1.3.0"',
    "}",
    "",
    'variable "cpc_endpoint" { type = string  default = "' + baseUrl + '" }',
    'variable "cpc_token"    { type = string  sensitive = true }',
    'variable "hostname"     { type = string }',
    'variable "cpu"          { type = number  default = 2 }',
    'variable "memory_gb"    { type = number  default = 2 }',
  ];
  if (kind !== "container") lines.push('variable "disk_gb"      { type = number  default = 50 }');
  if (isVm) {
    lines.push('variable "environment"  { type = string  description = "Network interface (GET /api/catalog/environments)" }');
    lines.push('variable "username"     { type = string  default = "appuser" }');
  }
  lines.push(
    "",
    'resource "null_resource" "cpc_' + kind + '" {',
    "  triggers = {",
    "    hostname = var.hostname",
    "    cpu      = var.cpu",
    "    memory   = var.memory_gb",
    "  }",
    "",
    "  provisioner \"local-exec\" {",
    '    interpreter = ["/bin/sh", "-c"]',
    "    command = <<-EOT",
    '      curl -sS -X POST "${var.cpc_endpoint}' + path + '" \\',
    '        -H "Authorization: Bearer ${var.cpc_token}" \\',
    '        -H "Content-Type: application/json" \\',
    "        -d '" + bodyJson + "'",
    "    EOT",
    "  }",
    "}",
    "",
  );
  return lines.join("\n");
}

function ansible(ctx) {
  const { baseUrl, kind, template, path, body } = ctx;
  const lines = [
    `# ${template.name} — provision via CPC (${kind})`,
    `# Run: ansible-playbook playbook.yml   (export CPC_TOKEN=<your PAT> first)`,
    `- name: Provision ${template.name} on Colruyt Private Cloud`,
    `  hosts: localhost`,
    `  gather_facts: false`,
    `  vars:`,
    `    cpc_endpoint: "${baseUrl}"`,
    `    cpc_token: "{{ lookup('env', 'CPC_TOKEN') }}"`,
    `    hostname: "my-${kind}-01"`,
    `    cpu: 2`,
    `    memory_gb: 2`,
  ];
  if (kind !== "container") lines.push(`    disk_gb: 50`);
  if (body.environment !== undefined) {
    lines.push(`    environment_iface: ""   # network interface, see /api/catalog/environments`);
    lines.push(`    username: "appuser"`);
  }
  lines.push(
    `  tasks:`,
    `    - name: Submit provisioning request`,
    `      ansible.builtin.uri:`,
    `        url: "{{ cpc_endpoint }}${path}"`,
    `        method: POST`,
    `        headers:`,
    `          Authorization: "Bearer {{ cpc_token }}"`,
    `        body_format: json`,
    `        body:`,
  );
  const idKey = kind === "stack" ? "stackId" : "templateId";
  const idVal = kind === "stack" ? template.id : template.id;
  const hostKey = kind === "stack" ? "hostnamePrefix" : "hostname";
  lines.push(`          ${idKey}: "${idVal}"`);
  lines.push(`          ${hostKey}: "{{ hostname }}"`);
  lines.push(`          cpu: "{{ cpu }}"`);
  lines.push(`          memoryGB: "{{ memory_gb }}"`);
  if (kind !== "container") lines.push(`          diskGB: "{{ disk_gb }}"`);
  if (body.environment !== undefined) {
    lines.push(`          environment: "{{ environment_iface }}"`);
    lines.push(`          username: "{{ username }}"`);
  }
  lines.push(
    `        status_code: [200, 202]`,
    `      register: cpc_result`,
    `    - name: Show result`,
    `      ansible.builtin.debug:`,
    `        var: cpc_result.json`,
    ``,
  );
  return lines.join("\n");
}

function pulumi(ctx) {
  const { baseUrl, kind, template, path } = ctx;
  const idKey = kind === "stack" ? "stackId" : "templateId";
  const hostKey = kind === "stack" ? "hostnamePrefix" : "hostname";
  const bodyObj = { [idKey]: template.id, [hostKey]: "my-" + kind + "-01", cpu: 2, memoryGB: 2 };
  if (kind !== "container") bodyObj.diskGB = 50;
  if (kind === "vm" && template.provider !== "internal") { bodyObj.environment = ""; bodyObj.username = "appuser"; }
  return [
    `// ${template.name} — provision via CPC (${kind})`,
    `// Pulumi program: set CPC_TOKEN in your environment before 'pulumi up'.`,
    `import * as command from "@pulumi/command";`,
    ``,
    `const endpoint = "${baseUrl}";`,
    `const token = process.env.CPC_TOKEN ?? "";`,
    `const payload = ${j(bodyObj)};`,
    ``,
    `const provision = new command.local.Command("provision-${kind}", {`,
    "  create: `curl -sS -X POST \"${endpoint}" + path + "\" -H \"Authorization: Bearer ${token}\" -H \"Content-Type: application/json\" -d '${JSON.stringify(payload)}'`,",
    `});`,
    ``,
    `export const result = provision.stdout;`,
    ``,
  ].join("\n");
}

function curl(ctx) {
  const { baseUrl, kind, template, path } = ctx;
  const idKey = kind === "stack" ? "stackId" : "templateId";
  const hostKey = kind === "stack" ? "hostnamePrefix" : "hostname";
  const bodyObj = { [idKey]: template.id, [hostKey]: "my-" + kind + "-01", cpu: 2, memoryGB: 2 };
  if (kind !== "container") bodyObj.diskGB = 50;
  if (kind === "vm" && template.provider !== "internal") { bodyObj.environment = ""; bodyObj.username = "appuser"; }
  return [
    `#!/usr/bin/env bash`,
    `# ${template.name} — provision via CPC (${kind})`,
    `# Usage: CPC_TOKEN=<your PAT> ./provision.sh`,
    `set -euo pipefail`,
    ``,
    `CPC_ENDPOINT="${baseUrl}"`,
    `: "${'${CPC_TOKEN:?Set CPC_TOKEN to your Personal Access Token}'}"`,
    ``,
    `# List your resources:`,
    `#   curl -H "Authorization: Bearer $CPC_TOKEN" "$CPC_ENDPOINT/api/resources"`,
    ``,
    `curl -sS -X POST "$CPC_ENDPOINT${path}" \\`,
    `  -H "Authorization: Bearer $CPC_TOKEN" \\`,
    `  -H "Content-Type: application/json" \\`,
    `  -d '${j(bodyObj)}'`,
    ``,
  ].join("\n");
}

export function generateIac({ tool, kind, template, baseUrl }) {
  const { path, body } = resolveTarget(kind, template);
  const ctx = { baseUrl, kind, template, path, body };
  const toolMeta = IAC_TOOLS.find((t) => t.id === tool) || IAC_TOOLS[0];
  let content;
  if (tool === "terraform") content = terraform(ctx);
  else if (tool === "ansible") content = ansible(ctx);
  else if (tool === "pulumi") content = pulumi(ctx);
  else content = curl(ctx);

  const safeName = String(template.name || template.id || "template")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  const base = toolMeta.filename.replace(/\.[^.]+$/, "");
  return {
    filename: `cpc-${safeName}-${base}.${toolMeta.ext}`,
    content,
    tool: toolMeta.id,
    language: toolMeta.ext,
  };
}
